"""Added tables

Revision ID: 543139b60233
Revises: 
Create Date: 2023-03-22 00:44:37.901699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from fastapi_users_db_sqlalchemy import generics


# revision identifiers, used by Alembic.
revision = "543139b60233"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", generics.GUID(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_full_name"), "user", ["full_name"], unique=False)
    op.create_table(
        "cheptel",
        sa.Column("id", postgresql.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("owner_id", postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cheptel_title"), "cheptel", ["title"], unique=False)
    op.create_index(op.f("ix_cheptel_type"), "cheptel", ["type"], unique=False)
    op.create_table(
        "hive",
        sa.Column("id", postgresql.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("owner_id", postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["cheptel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hive_title"), "hive", ["title"], unique=False)
    op.create_index(op.f("ix_hive_type"), "hive", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hive_type"), table_name="hive")
    op.drop_index(op.f("ix_hive_title"), table_name="hive")
    op.drop_table("hive")
    op.drop_index(op.f("ix_cheptel_type"), table_name="cheptel")
    op.drop_index(op.f("ix_cheptel_title"), table_name="cheptel")
    op.drop_table("cheptel")
    op.drop_index(op.f("ix_user_full_name"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
