package log

import (
	"bytes"
	"context"
	"net/http"

	"github.com/gaetanDubuc/beeckend/internal/log"
	"github.com/google/uuid"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"go.uber.org/zap/zaptest/observer"
)

type contextKey int

const (
	requestIDKey contextKey = iota
	correlationIDKey
)

type Logger struct {
	*zap.SugaredLogger
}

// With returns a logger based off the root logger and decorates it with the given context and arguments.
//
// If the context contains request ID and/or correlation ID information (recorded via WithRequestID()
// and WithCorrelationID()), they will be added to every log message generated by the new logger.
//
// The arguments should be specified as a sequence of name, value pairs with names being strings.
// The arguments will also be added to every log message generated by the logger.
func (l *Logger) With(ctx context.Context, args ...interface{}) log.Logger {
	if ctx != nil {
		if id, ok := ctx.Value(requestIDKey).(string); ok {
			args = append(args, zap.String("request_id", id))
		}
		if id, ok := ctx.Value(correlationIDKey).(string); ok {
			args = append(args, zap.String("correlation_id", id))
		}
	}
	return &Logger{l.SugaredLogger.With(args...)}
}

func (l *Logger) Named(name string) log.Logger {
	return &Logger{l.SugaredLogger.Named(name)}
}

// New creates a new logger ready for production using the default configuration.
func NewProduction() *Logger {
	l, _ := zap.NewProduction()
	return NewWithZap(l)
}

// New creates a new logger ready for development using the default configuration.
func NewDevelopment() *Logger {
	l, _ := zap.NewDevelopment()
	return NewWithZap(l)
}

// NewWithZap creates a new logger using the preconfigured zap logger.
func NewWithZap(l *zap.Logger) *Logger {
	return &Logger{l.Sugar()}
}

// NewForTest returns a new logger and the corresponding observed logs which can be used in unit tests to verify log entries.
func NewForTest() (*Logger, *observer.ObservedLogs, *bytes.Buffer) {
	pipeTo := &bytes.Buffer{}
	core, recorded := observer.New(zapcore.DebugLevel)
	core = zapcore.NewTee(
		core,
		zapcore.NewCore(zapcore.NewConsoleEncoder(zap.NewDevelopmentEncoderConfig()), zapcore.Lock(zapcore.AddSync(pipeTo)), zapcore.DebugLevel),
	)
	return NewWithZap(zap.New(core)), recorded, pipeTo
}

// WithRequest returns a context which knows the request ID and correlation ID in the given request.
func WithRequest(ctx context.Context, req *http.Request) context.Context {
	id := getRequestID(req)
	if id == "" {
		id = uuid.New().String()
	}
	ctx = context.WithValue(ctx, requestIDKey, id)
	if id := getCorrelationID(req); id != "" {
		ctx = context.WithValue(ctx, correlationIDKey, id)
	}
	return ctx
}

// getCorrelationID extracts the correlation ID from the HTTP request.
func getCorrelationID(req *http.Request) string {
	return req.Header.Get("X-Correlation-ID")
}

// getRequestID extracts the correlation ID from the HTTP request.
func getRequestID(req *http.Request) string {
	return req.Header.Get("X-Request-ID")
}
