info:
  contact: {}
paths:
  /cheptels:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: query
      summary: Query the user's cheptels
      tags:
      - Cheptel
swagger: "2.0"
